# Generated by Django 4.0.1 on 2022-03-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Cars/Design_Images'),
        ),
        migrations.AlterField(
            model_name='handbag',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Handbarg/Design_Images'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Shoes/Design_Images'),
        ),
    ]
