# Generated by Django 4.0.1 on 2022-03-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_alter_car_image_alter_handbag_image_alter_shoe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
